-- Create ICON_COLOR table
CREATE TABLE IF NOT EXISTS ICON_COLOR (
    iconColorId INT AUTO_INCREMENT PRIMARY KEY,
    red INT NOT NULL CHECK (red BETWEEN 0 AND 256),
    green INT NOT NULL CHECK (green BETWEEN 0 AND 256),
    blue INT NOT NULL CHECK (blue BETWEEN 0 AND 256)
);

-- Create TASK_STATUS table
CREATE TABLE IF NOT EXISTS TASK_STATUS (
    statusId INT AUTO_INCREMENT PRIMARY KEY,
    statusName VARCHAR(50) NOT NULL UNIQUE CHECK (statusName IN ('ACTIVE', 'COMPLETED', 'PAST'))
);

-- Create PROJECTS table
CREATE TABLE IF NOT EXISTS PROJECT (
    projectId INT AUTO_INCREMENT PRIMARY KEY,
    projectTitle VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(500),
    listOrder INT,
    iconColorId INT NOT NULL,
    FOREIGN KEY (iconColorId) REFERENCES ICON_COLOR(iconColorId)
);

-- Create TAGS table
CREATE TABLE IF NOT EXISTS TAG (
    tagId INT AUTO_INCREMENT PRIMARY KEY,
    tagName VARCHAR(255) NOT NULL UNIQUE,
    iconColorId INT NOT NULL,
    FOREIGN KEY (iconColorId) REFERENCES ICON_COLOR(iconColorId)
);

-- Create TASKS table
CREATE TABLE IF NOT EXISTS TASK (
    taskId INT AUTO_INCREMENT PRIMARY KEY,
    taskTitle VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(1000),
    statusId INT,
    priority INT CHECK (priority IN (1, 2, 3)),
    dueDate DATE CHECK (dueDate >= CURRENT_DATE),
    listOrder INT,
    projectId INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completedAt TIMESTAMP,
    FOREIGN KEY (statusId) REFERENCES TASK_STATUS(statusId),
    FOREIGN KEY (projectId) REFERENCES PROJECT(projectId)
);

CREATE TABLE IF NOT EXISTS WEEK_DAYS(
	weekDayId INT PRIMARY KEY,
	dayName VARCHAR(20) NOT NULL
);

-- Create RECURRING_TASKS table (allowing multiple weekdays per task ID via composite PK)
CREATE TABLE IF NOT EXISTS RECURRING_TASK (
    taskId INT NOT NULL,
    weekDayId INT NOT NULL,
    PRIMARY KEY (taskId, weekDayId),
    FOREIGN KEY (taskId) REFERENCES TASK(taskId),
    CONSTRAINT fk_recurring_task_week_days FOREIGN KEY (weekDayId) REFERENCES WEEK_DAYS(weekDayId)
);

-- Create REMINDERS table (1:1 relation with TASKS)
CREATE TABLE IF NOT EXISTS REMINDER (
    taskId INT PRIMARY KEY,
    remindAt TIMESTAMP NOT NULL,
    message VARCHAR(1000),
    FOREIGN KEY (taskId) REFERENCES TASK(taskId)
);

-- Create TASK_TAGS junction table (M:N relation between TASKS and TAGS)
CREATE TABLE IF NOT EXISTS TASK_TAG (
    taskId INT NOT NULL,
    tagId INT NOT NULL,
    PRIMARY KEY (taskId, tagId),
    FOREIGN KEY (taskId) REFERENCES TASK(taskId),
    FOREIGN KEY (tagId) REFERENCES TAG(tagId)
);

-- Create INBOX table
CREATE TABLE IF NOT EXISTS INBOX (
    inboxId INT AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(1000) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
