-- Instead of relying the Java code to check conflicts, just check them here. The file will run for one time only so it should not be a problem.
-- Insert ICON_COLOR records
INSERT INTO ICON_COLOR (red, green, blue) SELECT 255, 0, 0    WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 255 AND green = 0   AND blue = 0);    -- Red
INSERT INTO ICON_COLOR (red, green, blue) SELECT 0, 200, 83   WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 0   AND green = 200 AND blue = 83);   -- Green
INSERT INTO ICON_COLOR (red, green, blue) SELECT 33, 150, 243 WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 33  AND green = 150 AND blue = 243);  -- Blue
INSERT INTO ICON_COLOR (red, green, blue) SELECT 156, 39, 176 WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 156 AND green = 39  AND blue = 176);  -- Purple
INSERT INTO ICON_COLOR (red, green, blue) SELECT 255, 152, 0  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 255 AND green = 152 AND blue = 0);    -- Orange
INSERT INTO ICON_COLOR (red, green, blue) SELECT 244, 67, 54  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 244 AND green = 67  AND blue = 54);   -- Coral Red
INSERT INTO ICON_COLOR (red, green, blue) SELECT 0, 188, 212  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 0   AND green = 188 AND blue = 212);  -- Cyan
INSERT INTO ICON_COLOR (red, green, blue) SELECT 255, 235, 59 WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 255 AND green = 235 AND blue = 59);   -- Yellow
INSERT INTO ICON_COLOR (red, green, blue) SELECT 233, 30, 99  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 233 AND green = 30  AND blue = 99);   -- Pink
INSERT INTO ICON_COLOR (red, green, blue) SELECT 0, 150, 136  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 0   AND green = 150 AND blue = 136);  -- Teal
INSERT INTO ICON_COLOR (red, green, blue) SELECT 103, 58, 183 WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 103 AND green = 58  AND blue = 183);  -- Deep Purple
INSERT INTO ICON_COLOR (red, green, blue) SELECT 255, 87, 34  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 255 AND green = 87  AND blue = 34);   -- Deep Orange
INSERT INTO ICON_COLOR (red, green, blue) SELECT 96, 125, 139 WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 96  AND green = 125 AND blue = 139);  -- Blue Grey
INSERT INTO ICON_COLOR (red, green, blue) SELECT 121, 85, 72  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 121 AND green = 85  AND blue = 72);   -- Brown
INSERT INTO ICON_COLOR (red, green, blue) SELECT 76, 175, 80  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 76  AND green = 175 AND blue = 80);   -- Light Green
INSERT INTO ICON_COLOR (red, green, blue) SELECT 63, 81, 181  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 63  AND green = 81  AND blue = 181);  -- Indigo
INSERT INTO ICON_COLOR (red, green, blue) SELECT 0, 96, 100   WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 0   AND green = 96  AND blue = 100);  -- Dark Teal
INSERT INTO ICON_COLOR (red, green, blue) SELECT 255, 193, 7  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 255 AND green = 193 AND blue = 7);    -- Amber
INSERT INTO ICON_COLOR (red, green, blue) SELECT 171, 71, 188 WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 171 AND green = 71  AND blue = 188);  -- Orchid
INSERT INTO ICON_COLOR (red, green, blue) SELECT 38, 166, 154 WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 38  AND green = 166 AND blue = 154);  -- Medium Aquamarine
INSERT INTO ICON_COLOR (red, green, blue) SELECT 239, 108, 0  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 239 AND green = 108 AND blue = 0);    -- Dark Orange
INSERT INTO ICON_COLOR (red, green, blue) SELECT 30, 136, 229 WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 30  AND green = 136 AND blue = 229);  -- Dodger Blue
INSERT INTO ICON_COLOR (red, green, blue) SELECT 216, 27, 96  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 216 AND green = 27  AND blue = 96);   -- Crimson
INSERT INTO ICON_COLOR (red, green, blue) SELECT 85, 139, 47  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 85  AND green = 139 AND blue = 47);   -- Olive Green
INSERT INTO ICON_COLOR (red, green, blue) SELECT 69, 90, 100  WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 69  AND green = 90  AND blue = 100);  -- Slate
INSERT INTO ICON_COLOR (red, green, blue) SELECT 205, 220, 57 WHERE NOT EXISTS (SELECT 1 FROM ICON_COLOR WHERE red = 205 AND green = 220 AND blue = 57);   -- Lime

-- Insert TASK_STATUS records
INSERT INTO TASK_STATUS (statusName) SELECT 'ACTIVE'    WHERE NOT EXISTS (SELECT 1 FROM TASK_STATUS WHERE statusName = 'ACTIVE');
INSERT INTO TASK_STATUS (statusName) SELECT 'COMPLETED' WHERE NOT EXISTS (SELECT 1 FROM TASK_STATUS WHERE statusName = 'COMPLETED');
INSERT INTO TASK_STATUS (statusName) SELECT 'PAST'      WHERE NOT EXISTS (SELECT 1 FROM TASK_STATUS WHERE statusName = 'PAST');

-- Insert TAGS records
INSERT INTO TAG (tagName, iconColorId) SELECT 'Urgent', 1 WHERE NOT EXISTS (SELECT 1 FROM TAG WHERE tagName = 'Urgent');
INSERT INTO TAG (tagName, iconColorId) SELECT 'Home',   2 WHERE NOT EXISTS (SELECT 1 FROM TAG WHERE tagName = 'Home');
INSERT INTO TAG (tagName, iconColorId) SELECT 'Gym',    3 WHERE NOT EXISTS (SELECT 1 FROM TAG WHERE tagName = 'Gym');
INSERT INTO TAG (tagName, iconColorId) SELECT 'Coding', 4 WHERE NOT EXISTS (SELECT 1 FROM TAG WHERE tagName = 'Coding');

-- Insert WEEK_DAYS records
INSERT INTO WEEK_DAYS (weekDayId, dayName) SELECT 1, 'MONDAY'    WHERE NOT EXISTS (SELECT 1 FROM WEEK_DAYS WHERE weekDayId = 1);
INSERT INTO WEEK_DAYS (weekDayId, dayName) SELECT 2, 'TUESDAY'   WHERE NOT EXISTS (SELECT 1 FROM WEEK_DAYS WHERE weekDayId = 2);
INSERT INTO WEEK_DAYS (weekDayId, dayName) SELECT 3, 'WEDNESDAY' WHERE NOT EXISTS (SELECT 1 FROM WEEK_DAYS WHERE weekDayId = 3);
INSERT INTO WEEK_DAYS (weekDayId, dayName) SELECT 4, 'THURSDAY'  WHERE NOT EXISTS (SELECT 1 FROM WEEK_DAYS WHERE weekDayId = 4);
INSERT INTO WEEK_DAYS (weekDayId, dayName) SELECT 5, 'FRIDAY'    WHERE NOT EXISTS (SELECT 1 FROM WEEK_DAYS WHERE weekDayId = 5);
INSERT INTO WEEK_DAYS (weekDayId, dayName) SELECT 6, 'SATURDAY'  WHERE NOT EXISTS (SELECT 1 FROM WEEK_DAYS WHERE weekDayId = 6);
INSERT INTO WEEK_DAYS (weekDayId, dayName) SELECT 7, 'SUNDAY'    WHERE NOT EXISTS (SELECT 1 FROM WEEK_DAYS WHERE weekDayId = 7);
