-- Drop junction and 1:1 tables first to avoid foreign key constraint violations
DROP TABLE IF EXISTS TASK_TAG;
DROP TABLE IF EXISTS REMINDER;
DROP TABLE IF EXISTS RECURRING_TASK;

-- Drop child tables next
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS PROJECT;

-- Drop parent tables
DROP TABLE IF EXISTS TASK_STATUS;
DROP TABLE IF EXISTS ICON_COLOR;
DROP TABLE IF EXISTS INBOX;
