-- Drop junction and 1:1 tables first to avoid foreign key constraint violations
DROP TABLE IF EXISTS TASK_TAGS;
DROP TABLE IF EXISTS REMINDERS;
DROP TABLE IF EXISTS RECURRING_TASKS;

-- Drop child tables next
DROP TABLE IF EXISTS TASKS;
DROP TABLE IF EXISTS TAGS;
DROP TABLE IF EXISTS PROJECTS;

-- Drop parent tables
DROP TABLE IF EXISTS TASK_STATUS;
DROP TABLE IF EXISTS ICON_COLOR;
DROP TABLE IF EXISTS INBOX;
