#Vaadin Copilot Integration Runtime Properties
#Fri Sep 11 09:59:13 GMT+03:00 2026
endpoint=http\://127.0.0.1\:40141/vaadin/copilot-bc1b3c9c-a804-404d-92b7-1cd5086eb8b2
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
