#Vaadin Copilot Integration Runtime Properties
#Fri Aug 28 11:23:50 GMT+03:00 2026
endpoint=http\://127.0.0.1\:41183/vaadin/copilot-ff2a503b-393c-47c0-a70e-989025d5e6b7
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
